# https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/connect/kafka-connect.yaml

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  build:
    output:
      image: <imageAddress>
