apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-source-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  config:
    database.hostname: postgres.db
    database.port: 5432
    database.user: postgres
    database.password: postgres
    database.dbname : strimzi
    database.server.name: dbserver
