apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-source-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    connector.class: io.debezium.connector.postgresql.PostgresConnector
    tasks.max: 1
    database.hostname: postgres
    database.port: 5432
    database.user: postgres
    database.password: postgres
    database.dbname : postgres
    database.server.name: dbserver
    plugin.name: wal2json
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
