apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic
spec:
  version: 7.14.2
  count: 1
  elasticsearchRef:
    name: elastic
  http:
    service:
      spec:
        type: LoadBalancer