# https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/connect/kafka-connect.yaml

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092

  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status

    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true

    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1

  build:
    output:
      image: ankur198/strimzi-pgsql-connect-ankur:latest
      type: docker
      pushSecret: regcred
    plugins:
      - artifacts:
        - type: zip
          url: "https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.6.2.Final/debezium-connector-postgres-1.6.2.Final-plugin.zip"
        name: debezium-postgres-connector
  template:
    pod:
      imagePullSecrets:
        - name: regcred